### ISSUE TITLE
env vars do nothing

### ISSUE THREAD

**Issue by chrisdlangton** [JerryCai/arachni#7]
using

```yml
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: postgres
      DB_NAME: arachni
      DB_USER: pgroot
      DB_PASS: arachni

```

the app itself just ignores these...

```
arachni_1   | Couldn't create database for {"host"=>"localhost", "adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"arachni_production", "pool"=>50, "username"=>"arachni", "password"=>"secret"}
arachni_1   | rake aborted!
arachni_1   | PG::ConnectionBad: could not connect to server: Connection refused
arachni_1   | 	Is the server running on host "localhost" (127.0.0.1) and accepting
arachni_1   | 	TCP/IP connections on port 5432?
arachni_1   | could not connect to server: Cannot assign requested address
arachni_1   | 	Is the server running on host "localhost" (::1) and accepting
arachni_1   | 	TCP/IP connections on port 5432?

```

I'm going to go look for a docker container that actually runs the app... or build one myself as it appears this is a dead project, almost a year since last activity..
